# Define an initial amount of replicas of this guestbook.
replicaCount: 1

# Replace image values with customized versions.
image:
  repository: ghcr.io/patrickdappollonio/kubernetes-guestbook
  pullPolicy: IfNotPresent
  tag: latest

# BYOSecret: create and bring your own Kubernetes secret
# by providing its name. The contents of the secret are
# environment variables attached as-is to the application.
secretEnvOverride: ""

# Manually specify all values for the backend. Ensure
# either redis or mssql is provided.
backend:
  redis:
    enabled: false
    host: ""
    pass: ""
  mssql:
    enabled: false
    username: ""
    password: ""
    host: ""
    instance: ""
    database: ""

# Configure image pull secrets
imagePullSecrets: []

# Override deployment name
nameOverride: ""
fullnameOverride: ""

# Define if the deployment needs service account data
serviceAccount:
  create: false
  annotations: {}
  name: ""

# Pod specific settings
podAnnotations: {}
podSecurityContext: {}

# Configure all security contexts
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Define what kind of service it'll be used
service:
  type: ClusterIP
  port: 8080

# Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: kubernetes-guestbook.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Configure resource limits
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Configure horizontal pod autoscaler settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Define a node selector for the deployment
nodeSelector: {}

# Define tolerations for the deployment
tolerations: []

# Define affinity for the deployment
affinity: {}

# Sidecar containers
sidecarContainers: []

# Volumes and volume mounts
extraVolumes: []
extraVolumeMounts: []
