{{ if or (and .Values.backend.redis.host .Values.backend.redis.pass) .Values.backend.mssql.connstring }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guestbook.fullname" . }}-secret
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
data:
  {{- if and .Values.backend.redis.host .Values.backend.redis.pass }}
  REDIS_HOST: {{ .Values.backend.redis.host | b64enc | quote }}
  REDIS_PASS: {{ .Values.backend.redis.pass | b64enc | quote }}
  {{- end -}}
  {{- if .Values.backend.mssql.connstring }}
  MSSQL_CONNSTRING: {{ .Values.backend.mssql.connstring | b64enc | quote }}
  {{- end -}}
{{ end }}
