{{ if or .Values.backend.redis.enabled .Values.backend.mssql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guestbook.fullname" . }}-secret
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
data:
  {{- if .Values.backend.redis.enabled }}
  {{- with .Values.backend.redis.host }}
  REDIS_HOST={{.}}
  {{- end }}
  {{- with .Values.backend.redis.pass }}
  REDIS_PASS={{.}}
  {{- end }}
  {{- end }}

  {{- if .Values.backend.mssql.enabled }}
  {{- with .Values.backend.mssql.username }}
  SQL_USERNAME={{.}}
  {{- end }}
  {{- with .Values.backend.mssql.password }}
  SQL_PASSWORD={{.}}
  {{- end }}
  {{- with .Values.backend.mssql.instance }}
  SQL_INSTANCE={{.}}
  {{- end }}
  {{- with .Values.backend.mssql.host }}
  SQL_HOST={{.}}
  {{- end }}
  {{- with .Values.backend.mssql.database }}
  SQL_DATABASE={{.}}
  {{- end }}
  {{- end }}
{{ end }}
